# سكربت النشر التلقائي (Windows)
# الاستخدام:
#   $env:JOBS_DIR = "c:\path\to\jobs"
#   $env:VERCEL_TOKEN = "xxxxx"   # اختياري، للتشغيل الحقيقي
#   .\scripts\deploy.ps1 -JobId "abc12345"

param([Parameter(Mandatory = $true)][string]$JobId)

$JobsBase = if ($env:JOBS_DIR) { $env:JOBS_DIR } else { Join-Path (Get-Location) "..\..\jobs" }
$JobDir = Join-Path $JobsBase $JobId
$ProjectDir = Join-Path $JobDir "project"
$LogFile = Join-Path $JobDir "logs.txt"
$StatusFile = Join-Path $JobDir "status.json"

function Log { param([string]$Msg); $ts = (Get-Date).ToString("o"); \"[$ts] $Msg\" | Out-File -FilePath $LogFile -Append -Encoding utf8 }

if (-not (Test-Path $ProjectDir)) {
  Log "ERROR: no project folder for job $JobId"
  exit 1
}

if (-not (Test-Path $StatusFile)) {
  Log "ERROR: no status.json for job $JobId"
  exit 1
}

$statusLine = Get-Content $StatusFile | Select-String '"status":"([^"]+)"' -AllMatches | Select-Object -First 1
$status = if ($statusLine) { $statusLine.Matches[0].Groups[1].Value } else { "" }
if ($status -ne "build_success") {
  Log "INFO: skipping deploy because status is '$status' (expected build_success)"
  exit 0
}

Set-Location $ProjectDir

Log "Initializing git repo for deploy..."
git init | Out-Null
git add . | Out-Null
git commit -m "Auto-generated by Badr Forge (job $JobId)" | Out-Null 2>$null

$deployUrl = ""

if ($env:VERCEL_TOKEN) {
  Log "Deploying to Vercel..."
  $deployUrl = npx vercel --prod --yes --token=$env:VERCEL_TOKEN 2>&1 | Select-Object -Last 1
}
else {
  Log "(simulation) VERCEL_TOKEN not set; simulating deploy only."
  $deployUrl = "https://example.com/job-$JobId"
}

$deployedAt = (Get-Date).ToString("o")

@"{"status":"deployed","url":"$deployUrl","deployedAt":"$deployedAt"}"@ | Set-Content -Path $StatusFile -Encoding UTF8

Log "Deploy finished. URL: $deployUrl"
exit 0

