#!/bin/bash
# سكربت النشر التلقائي (Linux / Kwork)
# الاستخدام: JOBS_DIR=/path/to/jobs ./scripts/deploy.sh <jobId>

JOB_ID=$1
JOBS_BASE="${JOBS_DIR:-/home/user/jobs}"
JOB_DIR="$JOBS_BASE/$JOB_ID"
PROJECT_DIR="$JOB_DIR/project"
LOG_FILE="$JOB_DIR/logs.txt"
STATUS_FILE="$JOB_DIR/status.json"

if [ ! -d "$PROJECT_DIR" ]; then
  echo "[$(date -Iseconds)] ERROR: no project folder for job $JOB_ID" >> "$LOG_FILE"
  exit 1
fi

if [ ! -f "$STATUS_FILE" ]; then
  echo "[$(date -Iseconds)] ERROR: no status.json for job $JOB_ID" >> "$LOG_FILE"
  exit 1
fi

STATUS=$(grep -o '"status":"[^"]*"' "$STATUS_FILE" | head -1 | sed 's/\"status\":\"//;s/\"//')
if [ "$STATUS" != "build_success" ]; then
  echo "[$(date -Iseconds)] INFO: skipping deploy because status is '$STATUS' (expected build_success)" >> "$LOG_FILE"
  exit 0
fi

cd "$PROJECT_DIR" || exit 1

echo "[$(date -Iseconds)] Initializing git repo for deploy..." >> "$LOG_FILE"
git init >/dev/null 2>&1
git add . >/dev/null 2>&1
git commit -m "Auto-generated by Badr Forge (job $JOB_ID)" >/dev/null 2>&1 || true

DEPLOY_URL=""

if [ -n "$VERCEL_TOKEN" ]; then
  echo "[$(date -Iseconds)] Deploying to Vercel..." >> "$LOG_FILE"
  DEPLOY_URL=$(npx vercel --prod --yes --token="$VERCEL_TOKEN" 2>&1 | tail -1)
else
  echo "[$(date -Iseconds)] (simulation) VERCEL_TOKEN not set; simulating deploy only." >> "$LOG_FILE"
  DEPLOY_URL="https://example.com/job-$JOB_ID"
fi

DEPLOYED_AT=$(date -Iseconds)

cat > "$STATUS_FILE" << EOF
{
  "status": "deployed",
  "url": "$DEPLOY_URL",
  "deployedAt": "$DEPLOYED_AT"
}
EOF

echo "[$(date -Iseconds)] Deploy finished. URL: $DEPLOY_URL" >> "$LOG_FILE"
exit 0

